apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-testbed-runner
  labels:
    app.kubernetes.io/name: rhdh-testbed
    app.kubernetes.io/component: runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-testbed-runner
subjects:
  - kind: ServiceAccount
    name: rhdh-testbed-runner
    namespace: rhdh-testbed
